name: Chuck Norris Joke Logger

on:
  schedule:
    - cron: "10 14 * * 3"
  workflow_dispatch: # para ejecutarlo manualmente desde GitHub

permissions:
  contents: write # ⬅️ ESTO ES LO NUEVO

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python chuck_joke.py

      - name: Subir log actualizado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add chuck_jokes_log.txt
          git commit -m "Actualizar chiste 🤣" || echo "Nada que commitear"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
